=== DMoscicki/kubesman/kubernetes-json-schema-master/v1.30.2/podlist-v1.json
{
  "description": "PodList is a list of Pods.",
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "items"
  ],
  "type": "object",
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
      "enum": [
        "v1"
      ],
      "type": [
        "string",
        "null"
      ]
    },
    "items": {
      "description": "List of pods. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md",
      "items": {
        "$ref": "./_definitions.json#/definitions/io.k8s.api.core.v1.Pod"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
      "enum": [
        "PodList"
      ],
      "type": [
        "string",
        "null"
      ]
    },
    "metadata": {
      "$ref": "./_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta",
      "description": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    }
  },
  "x-kubernetes-group-version-kind": [
    {
      "group": "",
      "kind": "PodList",
      "version": "v1"
    }
  ]
}

=== DMoscicki/kubesman/k8s-protos/testdata/podlist.json
{
    "apiVersion": "v1",
    "kind": "PodList",
    "metadata": {
      "resourceVersion": "6808"
    },
    "items": [
      {
        "apiVersion": "v1",
        "kind": "Pod",
        "metadata": {
          "creationTimestamp": "2024-10-27T10:11:47Z",
          "generateName": "coredns-6f6b679f8f-",
          "labels": {
            "k8s-app": "kube-dns",
            "pod-template-hash": "6f6b679f8f"
          },
          "managedFields": [
            {
              "apiVersion": "v1",
              "fieldsType": "FieldsV1",
              "fieldsV1": {
                "f:metadata": {
                  "f:generateName": {},
                  "f:labels": {
                    ".": {},
                    "f:k8s-app": {},
                    "f:pod-template-hash": {}
                  },
                  "f:ownerReferences": {
                    ".": {},
                    "k:{\"uid\":\"6530ee23-e66a-4211-afc1-e511d0a5130a\"}": {}
                  }
                },
                "f:spec": {
                  "f:affinity": {
                    ".": {},
                    "f:podAntiAffinity": {
                      ".": {},
                      "f:preferredDuringSchedulingIgnoredDuringExecution": {}
                    }
                  },
                  "f:containers": {
                    "k:{\"name\":\"coredns\"}": {
                      ".": {},
                      "f:args": {},
                      "f:image": {},
                      "f:imagePullPolicy": {},
                      "f:livenessProbe": {
                        ".": {},
                        "f:failureThreshold": {},
                        "f:httpGet": {
                          ".": {},
                          "f:path": {},
                          "f:port": {},
                          "f:scheme": {}
                        },
                        "f:initialDelaySeconds": {},
                        "f:periodSeconds": {},
                        "f:successThreshold": {},
                        "f:timeoutSeconds": {}
                      },
                      "f:name": {},
                      "f:ports": {
                        ".": {},
                        "k:{\"containerPort\":53,\"protocol\":\"TCP\"}": {
                          ".": {},
                          "f:containerPort": {},
                          "f:name": {},
                          "f:protocol": {}
                        },
                        "k:{\"containerPort\":53,\"protocol\":\"UDP\"}": {
                          ".": {},
                          "f:containerPort": {},
                          "f:name": {},
                          "f:protocol": {}
                        },
                        "k:{\"containerPort\":9153,\"protocol\":\"TCP\"}": {
                          ".": {},
                          "f:containerPort": {},
                          "f:name": {},
                          "f:protocol": {}
                        }
                      },
                      "f:readinessProbe": {
                        ".": {},
                        "f:failureThreshold": {},
                        "f:httpGet": {
                          ".": {},
                          "f:path": {},
                          "f:port": {},
                          "f:scheme": {}
                        },
                        "f:periodSeconds": {},
                        "f:successThreshold": {},
                        "f:timeoutSeconds": {}
                      },
                      "f:resources": {
                        ".": {},
                        "f:limits": {
                          ".": {},
                          "f:memory": {}
                        },
                        "f:requests": {
                          ".": {},
                          "f:cpu": {},
                          "f:memory": {}
                        }
                      },
                      "f:securityContext": {
                        ".": {},
                        "f:allowPrivilegeEscalation": {},
                        "f:capabilities": {
                          ".": {},
                          "f:add": {},
                          "f:drop": {}
                        },
                        "f:readOnlyRootFilesystem": {}
                      },
                      "f:terminationMessagePath": {},
                      "f:terminationMessagePolicy": {},
                      "f:volumeMounts": {
                        ".": {},
                        "k:{\"mountPath\":\"/etc/coredns\"}": {
                          ".": {},
                          "f:mountPath": {},
                          "f:name": {},
                          "f:readOnly": {}
                        }
                      }
                    }
                  },
                  "f:dnsPolicy": {},
                  "f:enableServiceLinks": {},
                  "f:nodeSelector": {},
                  "f:priorityClassName": {},
                  "f:restartPolicy": {},
                  "f:schedulerName": {},
                  "f:securityContext": {},
                  "f:serviceAccount": {},
                  "f:serviceAccountName": {},
                  "f:terminationGracePeriodSeconds": {},
                  "f:tolerations": {},
                  "f:volumes": {
                    ".": {},
                    "k:{\"name\":\"config-volume\"}": {
                      ".": {},
                      "f:configMap": {
                        ".": {},
                        "f:defaultMode": {},
                        "f:items": {},
                        "f:name": {}
                      },
                      "f:name": {}
                    }
                  }
                }
              },
              "manager": "kube-controller-manager",
              "operation": "Update",
              "time": "2024-10-27T10:11:47Z"
            },
            {
              "apiVersion": "v1",
              "fieldsType": "FieldsV1",
              "fieldsV1": {
                "f:status": {
                  "f:conditions": {
                    ".": {},
                    "k:{\"type\":\"PodScheduled\"}": {
                      ".": {},
                      "f:lastProbeTime": {},
                      "f:lastTransitionTime": {},
                      "f:message": {},
                      "f:reason": {},
                      "f:status": {},
                      "f:type": {}
                    }
                  }
                }
              },
              "manager": "kube-scheduler",
              "operation": "Update",
              "subresource": "status",
              "time": "2024-10-27T10:11:47Z"
            },
            {
              "apiVersion": "v1",
              "fieldsType": "FieldsV1",
              "fieldsV1": {
                "f:status": {
                  "f:conditions": {
                    "k:{\"type\":\"ContainersReady\"}": {
                      ".": {},
                      "f:lastProbeTime": {},
                      "f:lastTransitionTime": {},
                      "f:status": {},
                      "f:type": {}
                    },
                    "k:{\"type\":\"Initialized\"}": {
                      ".": {},
                      "f:lastProbeTime": {},
                      "f:lastTransitionTime": {},
                      "f:status": {},
                      "f:type": {}
                    },
                    "k:{\"type\":\"PodReadyToStartContainers\"}": {
                      ".": {},
                      "f:lastProbeTime": {},
                      "f:lastTransitionTime": {},
                      "f:status": {},
                      "f:type": {}
                    },
                    "k:{\"type\":\"Ready\"}": {
                      ".": {},
                      "f:lastProbeTime": {},
                      "f:lastTransitionTime": {},
                      "f:status": {},
                      "f:type": {}
                    }
                  },
                  "f:containerStatuses": {},
                  "f:hostIP": {},
                  "f:hostIPs": {},
                  "f:phase": {},
                  "f:podIP": {},
                  "f:podIPs": {
                    ".": {},
                    "k:{\"ip\":\"10.244.0.2\"}": {
                      ".": {},
                      "f:ip": {}
                    }
                  },
                  "f:startTime": {}
                }
              },
              "manager": "kubelet",
              "operation": "Update",
              "subresource": "status",
              "time": "2024-10-28T17:25:53Z"
            }
          ],
          "name": "coredns-6f6b679f8f-g467d",
          "namespace": "kube-system",
          "ownerReferences": [
            {
              "apiVersion": "apps/v1",
              "blockOwnerDeletion": true,
              "controller": true,
              "kind": "ReplicaSet",
              "name": "coredns-6f6b679f8f",
              "uid": "6530ee23-e66a-4211-afc1-e511d0a5130a"
            }
          ],
          "resourceVersion": "6733",
          "uid": "b4f2358e-cbb3-42de-8191-4497c32b53d9"
        },
        "spec": {
          "affinity": {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [
                {
                  "podAffinityTerm": {
                    "labelSelector": {
                      "matchExpressions": [
                        {
                          "key": "k8s-app",
                          "operator": "In",
                          "values": [
                            "kube-dns"
                          ]
                        }
                      ]
                    },
                    "topologyKey": "kubernetes.io/hostname"
                  },
                  "weight": 100
                }
              ]
            }
